version: "3.7"

services:
  node-ts-otimizado:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: negociacoes-study-ts
    volumes:
      - ./:/app/src
      - ./servidor-api:/app/servidor-api
      - ./dist:/app/dist
      - ./app:/app/app
    ports:
      - "3000:3000"
    command: npm start
