version: '3.7'
services:
  negociacoes-site:
    build:
      context: ./packages/negociacoes-site
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./packages/negociacoes-site/src:/usr/src/app/src
      - ./packages/negociacoes-site/dist:/usr/src/app/dist
    environment:
      - PORT=3000
    command: npm run start:dev
    tty: true
    networks:
      - negociacoes-network

  negociacoes-api:
    build:
      context: ./packages/negociacoes-api
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    volumes:
      - ./packages/negociacoes-api/app:/usr/src/app/app
      - ./packages/negociacoes-api/config:/usr/src/app/config
    environment:
      - PORT=3000
    command: npm run start:dev
    tty: true
    networks:
      - negociacoes-network

networks:
  negociacoes-network:
