version: '3.7'
services:
  negociacoes-site:
    build:
      context: ./negociacoes-site
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./negociacoes-site/app:/usr/src/app/app
      - ./negociacoes-site/dist:/usr/src/app/dist
    environment:
      - PORT=3000
    command: npm run start:dev
    tty: true
    networks:
      - negociacoes-network

  negociacoes-api:
    build:
      context: ./negociacoes-api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./negociacoes-api/app:/usr/src/app/app
      - ./negociacoes-api/config:/usr/src/app/config
    environment:
      - PORT=3001
    command: npm run start:dev
    tty: true
    networks:
      - negociacoes-network

networks:
  negociacoes-network:
